apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secrets
  namespace: customer-service
  labels:
    app: customer-service
type: Opaque
data:
  DB_HOST: Y3VzdG9tZXItc2VydmljZS1yZHMueHh4eHh4LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: amp3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=
  NEW_RELIC_LICENSE_KEY: YWJjMTIzNDU2Nzg5MA==
